name: Bug Report
description: Report an issue or unexpected behavior that occurs within the application
title: "[Bug]: "
labels: "bug"
body:
  - type: markdown
    attributes:
      value: |
        **README: Before You Submit Your Issue**
        - Please check other open and closed issues for a similar bug before reporting a new one.
        - Make sure you are on the latest release of FreeTube before submitting an issue.
  - type: checkboxes
    id: guidelines
    attributes:
      label: Guidelines
      description: By submitting this issue, you agree with the checkboxes below
      options:
        - label: This issue is not a duplicate
          required: true
        - label: I'm using the latest version
          required: true
